### ISSUE TITLE
something wrong with sweeping wind in SIM

### ISSUE THREAD

**Issue by Gogomoihey** [d07RiV/d3planner#114]
hi !

can't generate stack vortex (imo, crit don't generate stack in sim)

test with tempest rush with sunwuko 6p + balance weapon (always crit on 3 or less ennemis hit)

so, i would have always 3 stack sweeping wind, but first hit always consume the stack and sim need reload all the time sweeping wind

thx for all :)

**Comment by d07RiV** [comment]
Can you post a link to the simulation?

I suspect the stack is being used up by SWK set bonus before it has a chance to refresh via crits. Does it work differently in-game?

**Comment by Gogomoihey** [comment]
but in game, i have no problem for maintain sweeping wind stack

but in simulation, stack always go off... (make an option to force sweeping wind stay at max stack)

thx a lot

**Comment by dominiklohmann** [comment]
If you add the condition "Buff stacks of Sweeping Wind > 1"  to Wave of Light in the Skill Rotation, you force it to never be cast when at 0 or 1 Sweeping Wind stacks.

**Comment by Gogomoihey** [comment]
i use tempest rush, condition dont work, channeling skill :/

**Comment by tw33dl3dee** [comment]
Can you post a link to your profile with simulation?

**Comment by d07RiV** [comment]
Just making sure, TR consumes a stack on every tick, or only when you start channeling? I think last time I asked this the answer was on every tick, but I never checked it since.

Pretty sure the condition should work on any skill, but it might cause you to never use TR again as the belt won't give you any stacks when you're close to enemies and not attacking them.
