### ISSUE TITLE
Can we model Exploding Palm?

### ISSUE THREAD

**Issue by Andy88488** [d07RiV/d3planner#186]
I'm trying an Exploding Palm build http://www.d3planner.com/345537055. I'm using the Impending Doom rune, which does no damage until death, then provides a massive explosion of damage. I'm finding this very powerful in-game, but I can't figure out how to model it in the Planner. The EP's effectiveness is based on (1) lots of density, and (2) killing white mobs. The simulator is showing EP as being 1.08% of my damage, and I can tell you that this is definitely NOT the case. 

So can the simulator model EP, and if so, do I need to modify the parameters to make this work?

**Comment by d07RiV** [comment]
Okay there were a few bugs with it that I just fixed.

In the simulator, EP is always applied to the first target without the debuff, but the 'Buff stacks' condition only checks the debuff on the first target (in your case, the elite that never dies). You need to use 'Debuff targets' instead, and make it equal to the actual number of targets in the simulation (4). Also, you should probably adjust the 'death rate' parameter in events, because the Auto setting is a bit weird.

At 10 deaths/minute EP comes out at around 10% damage - does that seem right?

**Comment by Andy88488** [comment]
Thanks for getting back to me on this. I may not be understanding how to use the Debuff Targets option, but I am getting 39 uses of EP but no damage. As far as whether 10% damage for EP makes sense, that's really, really hard to say. I'm only recently playing EP/Inna's build. As I ramp up in difficulty level, I'm finding that my Mystic Allies kill less and less, and EP kills more and more. Single white mobs are killed by my allies before I can even get to them. But I blow up groups with great regularity. 

I guess that has to do with Monster Health, which is kind of a semi-unknown in the Simulator. Also, it depends on the cluster size. I recently did the Cow Level on T12, and I was exploding whole screens, dozens and dozens of cows.

**Comment by Andy88488** [comment]
Bump

**Comment by d07RiV** [comment]
Yep, monster health is calculated in a weird way unless you explicitly specify it, so group calculations are kinda hard to do correctly.
