### ISSUE TITLE
Call of the Ancients : Ancients' Fury Rage Regen not working

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#21]
The rune does not provide any rage if selected as a skill, but works correctly if active via the Fury of the Ancients shoulders.

**Comment by dominiklohmann** [comment]
Relevant function that is called: https://github.com/d07RiV/d3planner/blob/master/simulator/barbarian.js#L842-L856

```javascript
var info = Sim.castInfo();
if ((info && info.rune === "c") || Sim.stats.leg_furyoftheancients) {
    Sim.addResource(4);
}
```

Probably means that `Sim.castInfo()` fails for Ancients' on hit effects.

**Comment by d07RiV** [comment]
I fixed it yesterday: 7bb0a276bcb67c4999ab86f38d830e75b82116b4

The quoted code is part of the fix, but it seems that I forgot to upload it :(

**Comment by plopinou** [comment]
Is there a certain time to wait to see the actual changes you're uploading to the site due to the cache ?

**Comment by dominiklohmann** [comment]
http://www.d3planner.com/sim/barb Go there and reload the site, that should do the job.

**Comment by plopinou** [comment]
Even after going there, I see no change. But I tested it with a browser with which I've never gone to d3planner, and the fix is there. So there might be some cache problem somewhere else.
Thank you anyway for your tip dominiklohmann :)

**Comment by plopinou** [comment]
So, I could test some specs with Ancient's Fury directly selected as a rune, and it seems that if the rage is now gained correctly, it also adds the effect of the rune next to it : Duty of the clan.

You can see it on the link you provided : http://www.d3planner.com/814927586 

On the contrary, selecting the Duty to the Clan rune does not change anything (no dps increase, no uptime).

**Comment by d07RiV** [comment]
What dominiklohmann said, but the correct link is http://www.d3planner.com/sim/barbarian
The /barb link actually gives the simulator core, instead of the barbarian module.

I used to have a system to bypass cache, but it didn't work very well and I ditched it when I reorganized the way content is served, so now most simulator updates take time to make it through properly, since browsers do not reload web workers even on Ctrl+F5 for some reason. You can force the refresh by opening the page manually, refreshing it, and then opening d3planner in a new tab (the old tab will still have the old script for some reason).
