### ISSUE TITLE
Stats are off

### ISSUE THREAD

**Issue by sourcec0de** [d07RiV/d3planner#215]
Hey, just wanted to run this by you guys.

I simply imported my stats and everything is off by **ALOT**.

### Actual Stats
https://us.battle.net/d3/en/profile/R4PTR-1295/hero/88902264
Damage 592,153
Toughness 1,116,9200
Recovery 831,217

### Imported Stats
https://d3planner.com/120175703
Damage 888,998
Toughness 19,482,775
Recovery 2,400,475

I reset paragon and and didn't assign anything inside d3planner.

**Comment by d07RiV** [comment]
There are a lot of switches in the Skills tab that affect your damage and toughness. I'm not sure which skills are included in the online profile, but if you compare the values to what you see in-game with the same set of buffs, it should be a lot closer.

Here's something that looks close to what you currently have in your profile: https://d3planner.com/340325687

Toughness can be off slightly because they have a weird way of calculating the effect of individual resistance (i.e. you actually care about things like, say, toughness vs ranged poison damage, or melee physical, etc, and the overall number is some estimate that tries to average everything). Healing is also weird in a similar way.
