### ISSUE TITLE
Multiple items missing correct max base armor

### ISSUE THREAD

**Issue by Runisco** [d07RiV/d3planner#22]
Example, Crashing rain on the site has max 509 default armor, however in the game it can have (from those I've seen) up to 900

**Comment by d07RiV** [comment]
If an item has an armor roll, it will display the total armor in place of the base value (so you can only find out the real base value by subtracting one from the other).

There is also an issue with some belts using armor rolls for Mighty Belts instead, but I can't find the pattern. The max value for mighty belts is 675, so that doesn't seem to be the issue here. Currently the only exceptions I'm aware of are Thundergod's Vigor and Belt of the Trove.
