### ISSUE TITLE
[API] JSON Data

### ISSUE THREAD

**Issue by Xqzmeplz** [d07RiV/d3planner#285]
Hello,
is there a way to get the following information for all items
- Id
- Quality (Legendary, Set, ...)
- Type

I want to query the https://dev.battle.net items API but there is no way to query all equip able legendary/set items.
Previously i was scraping the data from the https://eu.battle.net/d3/en/item/ not the best way.

Regards,
Xqzmeplz

**Comment by d07RiV** [comment]
Try these
http://d3planner.com/game/json

It doesn't have item type, though. You can find them here instead (in a more verbose form):
http://d3planner.com/game/raw/47710/Items_Legendary

**Comment by Xqzmeplz** [comment]
Oh, i did not know about the second link.
What exactly is described with the following parameters inside http://d3planner.com/game/json
- drop_level
- drop_weight
- trivial

**Comment by d07RiV** [comment]
* drop_level - x118 in the original data, base item level (probably minimum mLVL that can drop the item, but more importantly it seems to be the level requirement to be able to gamble for that item). Note that it is only correct for the latest build, since previously I used a different variable for it.
* drop_weight - relative weight for the item drop, determines the odds of getting that specific item compared to other items of the same type. Also relevant for gambling.
* trivial - not an equippable/socketable item.

**Comment by Xqzmeplz** [comment]
Thank you very much,
Keep up the good work ! :)
