### ISSUE TITLE
zeis legendary gem erroneous calculations?

### ISSUE THREAD

**Issue by dpastern** [d07RiV/d3planner#338]
Zeis increases dmg the further the target is away from your character, up to the maximum of 50 yards.  

When equipping zeis on my character to test, and setting the distance (under simulation) to 10 yards, zeis does MORE dmg than if the distance slider is set to 50 yards.

Unless I am mistaking either how d3planner works, or the mechanics of the lgem in question, d3planner's simulation calcs seem to be wrong.  

see:

https://www.d3planner.com/555752234

for example, swap out gogok for zeis on the amulet.  Go to simulation tab and set distance to 10 yards and run the sim, then 50 yards and run the sim.  Damage for 10 yards is much higher than for 50 yards.

**Comment by d07RiV** [comment]
You have BotT and Cull the Weak, but no way to slow targets at long range.

**Comment by dpastern** [comment]
But - I set distance to 10 yards, which should be within the radius for BotT to slow and affect mobs.  So, Zeis should work, albeit at a low dmg rate, but it isn't changing the elemental DPS or sim numbers.  I'm not worried about distant targets, impale s6 isn't a ranged attacker.  i was trying to see what zeis would do at 10 yards dps wise, but unless I'm doing something wrong, d3planner doesn't calculate it.

**Comment by dpastern** [comment]
Why gogok removed @ 10 yards?  now I'm confused (it is late here, after midnight).  I'd go with gogok/zeis/trapped for the 10 yard test (vs gogok/powerful/trapped).  Given that it's 10 yards, I know powerful is a better option (both DPS and toughness/recovery wise), I was just curious as to why I couldn't see a DPS differential @ 10 yards when I tested it.

Thanks for the mention on chilled target status - I didn't even know this existed .  My s15 DH doesn't have any target status effectors,  My NS One does though (slow, chilled, immobilze and stun).

**Comment by iThinkiWin** [comment]
> Why gogok removed @ 10 yards? now I'm confused (it is late here, after midnight). I'd go with gogok/zeis/trapped for the 10 yard test (vs gogok/powerful/trapped). Given that it's 10 yards, I know powerful is a better option (both DPS and toughness/recovery wise), I was just curious as to why I couldn't see a DPS differential @ 10 yards when I tested it.
> 
> Thanks for the mention on chilled target status - I didn't even know this existed . My s15 DH doesn't have any target status effectors, My NS One does though (slow, chilled, immobilze and stun).

Really don't understand why you're not understanding on simulator No distance is not effecting Gogok at all, its always "1482.86% Uptime" simulator page, bottom left after hitting start, the issue is monsters beyond the 15-18 Yard range of monster size + distance are not being slowed by anything as the slow effect from Bane of the trapped has limited range, so the Passive as he mentioned above "Cull the Weak" is no longer being applied so you lose 20% DMG increase
you can see this by instead maxing secondary effect on weapon and so on "Slow on Hit", and you will see damage increase from distances beyond the 15-18 wall.

**Comment by dpastern** [comment]
I think you're misunderstanding me here.

1.  I know trapped will have a minimal effect on ranged mobs

2.  I know that gogok is not affected by distance.  

I asked why Gogok was removed from your prior testing.  The reason why I say that, is because I'm trying to compare the *total* dmg (from all 3 leg gems) in both the case of trapped/gogok/powerful and trapped/gogok/zeis.  

My original bug report indicated that using zeis did not show any change in sim dmg (vs only using gogok/trapped), even WHEN the distance was set to 10 yards.  Therefore, my logical assumption was that d3planner wasn't registering the 10 yard limit that I set in sim and thus not showing zei's dmg.  

I hope that makes sense?

**Comment by iThinkiWin** [comment]
No drop the passive Cull the weak and redo your testing, you are not reading things right, the gems are and have been applying as intended
No Cull the Weak- @ 0 yards with Powerful/Trap/Zei
https://www.d3planner.com/311561590 | 1299.946 B
No Cull the Weak- @ 10 yards with Powerful/Trap/Zei
https://www.d3planner.com/212291065 | 1411.261 B
Cull the Weak- @ 0 yards with Powerful/Trap/Zei | 1559.935 B
Cull the Weak- @ 10 yards with Powerful/Trap/Zei | 1693.513 B
Cull the Weak- @ 18 yards (Bane of the Trapped Limit) with Powerful/Trap/Zei | DPS: 1833.118 B
Cull the Weak- @ 19 yards (over Bane of the Trapped Limit) with Powerful/Trap/Zei | DPS: 1063.249 B

Original comment from you "for example, swap out gogok for zeis on the amulet. Go to simulation tab and set distance to 10 yards and run the sim, then 50 yards and run the sim. Damage for 10 yards is much higher than for 50 yards." Because after 18 Yards as I said again you lose slow from Trap and lose the effect of Cull of the Weak. so running with out Cull the Weak should explain it better Bane of the Trap damage effect has No distance limit. only the slow effect 15(18 /w monster size) yards is lost.

**Comment by d07RiV** [comment]
I removed Gogok to put in Zei's, because that's what you said in your original post.

Trapped had two effects on the simulation - increased damage as long as enemies have slow/chill status, and applies slow status if enemies are in a 10yd range. As mentioned, you can manually add permanent status effects, which is generally there to simulate party play, since the sim should have a fairly accurate idea of what effects you apply yourself.

Also, there should have been a "slowed" line in the uptimes section, but it seems to be missing now, guess one of the updates broke it.

**Comment by dpastern** [comment]
All good.  As always, huge thanks for providing d3planner to the fans.  It's an invaluable tool.  Setting up sims still confuses the hell out of me though (hint: more presets for popular meta builds would be AWESOME!).

**Comment by iThinkiWin** [comment]
Majority of skills can be handled by Buffstacks, Skill, 0 to make it cast; so on skill (Storm Armor) add Buff Stacks, Storm Armor, =, 0  this will make it cast storm armor Only if the skill timer runs out, on other hand things like CoE you will do "Buffstack, CoE - The Element (lightning for example)",  >, 0
will make a skill only activate during Lightning rotation (fan of knives build uses that) fairly simple other than the things its incapable of doing currently and have to rely on making a timer based on other skills casts lol Mark for Death grim reaper rune will just make it 100% not work if more than 1 monster, and things like Ticking Firebirds 6 set bonus ~_~ tal rashas is easy since each element is its own ^

**Comment by d07RiV** [comment]
Note that skills with really long duration (Wizard buffs) are coded to have infinite duration and are applied initially, so you don't have to worry about adding rules for those.

**Comment by iThinkiWin** [comment]
Oh well that is good to know  👍
