### ISSUE TITLE
Any plan to "take damage", for The Invoker Set of the Crusader, for exemple ?

### ISSUE THREAD

**Issue by Nemesis666first** [d07RiV/d3planner#34]
Hi,

Like you know, The Invoker Set dont make a lot of damage, but if he play solo, he can take 100% of all damage, and MAKE damage like this.
But the simulator haven't this option.

Any plan for this :) !?

**Comment by d07RiV** [comment]
Yeah its in plans, I really need to add more events for things like these.

**Comment by d07RiV** [comment]
Okay I'm adding 'on hit' event, hope I don't miss any interactions.

Skills:
* ~~Revenge~~

Sets:

Items:
* Sanguinary Vambraces
* Pride's Fall
* Deathseer's Cowl
* Defender of Westmarch
* Freeze of Deflection
* Ivory Tower
* Wall of Man
* Akarat's Awakening
* Sublime Conviction
* The Oculus
* The Burning Axe of Sankis
* Death Watch Mantle
* The Cape of the Dark Knight
* Schaefer's Hammer (legacy)
* Vigilance
* Blood Brother
* Thundergod's Vigor

**Comment by dominiklohmann** [comment]
Here are some you've missed.

Items and skills that are based on health loss require a setting for incoming damage per hit because of shielding abilities like Magic Weapon: Deflection.

Items:
- Halo of Arlyse -- Requires setting for incoming damage per hit

Wizard:
- Ice Armor (all runes)
- Storm Armor (Reactive Armor)
- Energy Armor (Absorption)
- Illusionist -- Requires setting for incoming damage per hit

Monk:
- Mantra of Retribution

Crusader:
- Insourmountable

Barbarian:
- Overpower (Crushing Advance) -- Requires setting for incoming damage per hit
- Superstition

**Comment by d07RiV** [comment]
Oh yeah I only listed the items, I'm currently going through the list of skills and adding those that I implement.

Halo of Arlyse isn't listed because it doesn't know how much damage was dealt (same with Illusionist).

Not sure about Superstition because its only ranged and elemental damage (also it doesn't list the chance anywhere).

**Comment by dominiklohmann** [comment]
Couldn't you just add a slider for incoming damage as percentage of max health where you can select a range, and then just randomize from every hit from that damage range?

**Comment by d07RiV** [comment]
Yeah but we risk ending up with this

http://wallpapercave.com/wp/qlzwfWf.jpg

**Comment by dominiklohmann** [comment]
Maybe a checkbox for "Advanced Settings and/or Experimental Settings"? 

The simulator UI/UX has always kinda been an issue with how unintuitive it is to use (especially in regards to setting the skill rotation, some meanings of "Buff Stacks" for example are not very obvious). But I am not a designer – I don't know how to make it any better.

**Comment by d07RiV** [comment]
Yeah maybe.. I currently have a slider for rage/sec gained, so Superstition could be included there I guess. Not sure if Halo procs are very important, I'm not even sure if CC reduction is currently working correctly - didn't they revert some of the CC changes in 2.4?

**Comment by dominiklohmann** [comment]
They reverted them to the 2.3 settings for the second PTR patch, but on live it's just like Wyatt Cheng said they were gonna be... DR caps at 95% where targets become CC immune, falls of 5% per second, 1 second stun adds 10% DR and stuns for 1 second * (1-DR%). 

Halo of Arlyse is important because most wizard builds run it and some use it with the Frost Nova rune that gives you 10% CHC when you hit 5 or more enemies or the rune that gives 33% DIBS. Both have 100% uptime with Halo of Arlyse, and when you're playing a build with Obsidian Ring you never wanna use the skill by yourself, and that's something the simulator cannot do.

**Comment by d07RiV** [comment]
Oh.. uh.. I could just make it cast on every hit, since they're usually above 10% I guess. Or at least you can adjust the slider to how often you want it to proc, since Wizards don't tend to have other on-get-hit triggers.

**Comment by d07RiV** [comment]
Okay updated the list.

**Comment by dominiklohmann** [comment]
Very nice, thank you

**Comment by d07RiV** [comment]
What was the consensus on Sanguinary Vambraces? It still uses STR/400 scaling?

**Comment by dominiklohmann** [comment]
Yeah, it didn't change with the patch.

**Comment by d07RiV** [comment]
Blood Brother damage bonus is additive, right?

**Comment by dominiklohmann** [comment]
[Multiplicative according to someone on the old Mantis Bug Tracker](http://www.d3planner.com/mantisbt/view.php?id=412#c1179) - don't think this has changed since.

**Comment by d07RiV** [comment]
Uploaded, hope everything works >.>

**Comment by dominiklohmann** [comment]
What about adding a link the the issue tracker here directly to the simulator (maybe to the right of the "start" button), saying something like 

> **New**: Added getting hit events to the simulator. If you find any issues, [please let me know](https://github.com/d07RiV/d3planner/issues/).

**Comment by d07RiV** [comment]
Oh I can add it to global 'news' I guess. I've had that thing for a while but I very rarely use it because its, well, global, and I hesitate to use it for situational things like the simulator.

**Comment by d07RiV** [comment]
I'll assume that this is 'fixed' I guess.
