### ISSUE TITLE
Funerary Pick +2 hits means +200% damage

### ISSUE THREAD

**Issue by dtruffaut** [d07RiV/d3planner#349]
When I slot the skill Siphon blood, and I equip Funerary pick, there is no reflection on the damage made by the synergy {Siphon Blood + Funerary pick}.

It should, because Funerary Pick makes Siphon Blood drain from 2 additional targets.

Please provide, for this item, a selector of number of additional targets (1 or 2).

**Comment by d07RiV** [comment]
As I understand, this makes it drain from three *different* targets? The damage number is meant to reflect single target damage, or else any AOE ability would require a different output.

**Comment by d07RiV** [comment]
Those two affect the skill's single target damage, which is what the tooltip displays.

**Comment by Schtenk** [comment]
Both {Grim Scythe + Leger's Disdain} and {Blood Nova + Bloodtide Blade} only show damage on one of  the targets I.E those skills will do the damage shown to all targets hit. same thing for {Siphon Blood + Funerary pick} which will do the damage show to the three targets hit.

The sliders for {Grim Scythe + Leger's Disdain} and {Blood Nova + Bloodtide Blade} are there because the damage of the skills increase single target damage based on targets hit which {Siphon Blood + Funerary pick} does not.
