### ISSUE TITLE
Unable to import my profile

### ISSUE THREAD

**Issue by McArtyone** [d07RiV/d3planner#350]
Unable to import my profile-receive profile not found message.Few days ago i can do it, now not.

**Comment by krusty4president** [comment]
Im also having the same problem. Hope the devs can resolve it soon! :-) Thanks for a nice tool anyway.

**Comment by DamondSD** [comment]
I have been trying for two days now to import my profile, and received the "Profile not found" warning each time. I have checked and double checked that I am using the correct tag information. I have used Mac Safari V12.0.2 and Mac Chrome V71.0.3578.98. 

I really hope this issue is solved soon as I have just discovered this wonderful tool.

**Comment by CAP333** [comment]
Unable to import my profile-receive profile not found message.  BattleTag:  CAP#1894

**Comment by d07RiV** [comment]
Seems they reworked all their APIs again... and made it much harder to use this time. I'll see if I can work around it.

**Comment by CAP333** [comment]
Thanks, I would love to use D3 planner, again.

**Comment by d07RiV** [comment]
Okay everything seems to be in order now.

**Comment by jocloud31** [comment]
Hmm. I appear to still be having this issue. I've tried in Chrome and Firefox both. My battlenet account IS a US account as well. 

![2019-01-16 17_55_49-blizzard entertainment](https://user-images.githubusercontent.com/11720812/51286325-1e079100-19b8-11e9-95a0-abfe451ae835.png)

**Comment by CAP333** [comment]
Thanks!!!
