### ISSUE TITLE
Wizard Meteor and DH - Companion (Wolf rune)

### ISSUE THREAD

**Issue by Bonivur** [d07RiV/d3planner#372]
IF i import my LoN wiz with Star Pact meteor and select DH - COmpanion Wolf rune there is NO damage increase for Meteor.

**Comment by Bonivur** [comment]
And plz test DH - Mark of Death damage buff too. It seems to give too much damage (like it were a multiplier)

**Comment by d07RiV** [comment]
Companion was indeed broken, fixed it now.

What's wrong with MfD? It should add 15% additive damage buff, but since most other buffs are now multipliers it will indeed act almost as if it was a multiplier itself. But if you have a large amount of additive buffs (i.e. increased Meteor damage) then it will have much less effect.
