### ISSUE TITLE
Kanai's Cube

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#56]
The "Corrupted Ashbringer" cannot be cubed in diablo yet the planner allows it

**Comment by dominiklohmann** [comment]
It's in the [not yet implemented list](https://github.com/d07RiV/d3planner/blob/master/simulator/legs.txt) anyways, so this is just a UI issue.

**Comment by wow-config** [comment]
The i have a suggestion to add instead :)

Could you move the effects from the Kansai's Cube items to Skills & Effects like the other equipped items ? it seems a bit odd as many items have enable or stack count which affect damage values havng to jump forth and back all the time :)

**Comment by d07RiV** [comment]
@dominiklohmann: he means you can't cube it at all in the game (because its effect replaces your weapon with Ashbringer, which probably causes animation issues when you have other weapons equipped).

I could make it un-cubable but I don't think its a big issue anyway.

@wow-config: Yeah I'm not too happy with how cube items are separate, I used to have it in skills & effects before but too many people complained that it was too "hidden" and many people just couldn't find it.

I think the best solution would be to duplicate it so it appears in both places at the same time.

**Comment by dominiklohmann** [comment]
> because its effect replaces your weapon with Ashbringer, which probably causes animation issues when you have other weapons equipped

I get your point, just never considered that as a reason. You can't even see the effect in Archon for example.

**Comment by wow-config** [comment]
> because its effect replaces your weapon with Ashbringer, which probably causes animation issues when you have other weapons equipped.

What i meant was its presence could confuse newer players but as he explained it is just a UI issue.
