### ISSUE TITLE
PTR : BotS is now stacking on each WW tick

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#72]
Just confirmed it on the pvp zone in Act 1 with 2 accounts while checking some other things : WW is now stacking Bane of the Stricken at an incredible speed : exactly once per tick.

_Test setup :_
- hack in cube with ~2k thorns on gear to get a perfectly stable damage number
- low strength and 4p IK to get infinite WotB
- 2 low level crafted 1.3 APS axe
- 6% AS from paragon
- level 72 BotS -> 1.52% more damage per proc

This puts me right in the middle of the 10 FPA breakpoint for WW while under WotB.
I prefer to be in the middle because the game engine can screw up BotS procs if you're too close to a breakpoint (saw this behavior multiple time while checking numbers on videos).

_Testing :_
- hit the other player once, gets 1853 damage from hack
- WW for ~1mn
- check in video the exact frame count doing WW ->found 3720 frames exactly
- end damage is ~12300 after hitting once again the other player (reminder for next time: enable the long floating combat numbers)

_Result :_
each stricken stack should bring me 1853*0.0152 = 28.1656 more damage, that's what I can check if I simply use bash and go slowly after delog/relog.
In 62 s, or 3720 frames, BotS stacked (~12300-1853)/28.1656 = ~371 times. This is a near perfect result with a 10 FPA WW animation.

_Conclusion :_

**BotS now stacks once per WW tick**

It may be better to wait for an official confirmation before correcting this, it may not be intended.
Posted this on the official forum too to get some visibility.

**Comment by dominiklohmann** [comment]
They changed Bane of the Strickens internal cooldown to `ceil(((anim-length - 1) / anim-length) * (60 / (atk-speed * skill-multipliers)))`. Before that, it was `ceil(0.9 * (60 / atk-speed))`.

The change made it so attacks with an attack speed coefficient greater than 1.0 (e.g. Whirlwind) and attacks that had their attack speed buffed separately from the character sheet attack speed (e.g. Monk Generator skills with Alacrity) no longer cause desync between hits and Bane of the Stricken procs.

This change was actually made in 2.4 already, not sure whether this was not happening correctly with Whirlwind already. It is the intended behaviour as per Wyatt Cheng, who posted on the 2.4 PTR Feedback forums about making Bane of the Strickens internal cooldown scale with `skill attack speed` instead of `0.9 * sheet attack speed`.

Not sure how this is currently implemented on d3planner, @d07RiV?

**Comment by plopinou** [comment]
WW is ticking only once every 3 ticks in the sim, and it seems that it's that way on the live 2.4 too.
I didn't play that much with barb this season (in fact I didn't play much at all), so I don't know if this specific to the 2.4.1 or not.
It seems so because I didn't read anywhere on the barb official forum or the reddit that WW was stacking BotS very fast.

**Comment by plopinou** [comment]
Ok so I got some confirmation on the official forums that it's already been the case since the 2.4.0 is out. It's simply that the information wasn't well shared in the community :)
So the sim should be updated to reflect that fact, since it's been live for 3 months.

**Comment by d07RiV** [comment]
The formula you listed doesn't seem to support this though, unless I'm doing it wrong?

If Whirlwind animation is 20 frames, and attack speed is 1, then you would still be getting a stack per second, since ceil(19/20*60) = 57.

**Comment by vaelrock** [comment]
It seems it's in fact currently bugged since 2.4 (~3 months). No other channeling spell with low FPA is behaving in the same way.
http://us.battle.net/d3/en/forum/topic/20743026327
Nubtro tested some other spells of other classes in the 14th post, so it's just a specificity to WW.

I changed my github account BTW, to a personal one instead of the one for my work.

**Comment by d07RiV** [comment]
Ah I could just make a special case for WW then.
